name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 16 ]
    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v2
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: build-jar
        run: mvn -B install
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 16
      - name: create-javadoc
        run: mvn -B javadoc:javadoc
      - uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs
